spring:
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848 # nacos注册中心
      username: nacos
      password: nacos
      discovery:
        namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0
        group: DEFAULT_GROUP
        ip: 192.168.150.1
  config:
    import:
      - nacos:shared-spring.yaml
      - nacos:shared-redis.yaml
      - nacos:shared-mybatis.yaml
      - nacos:shared-logs.yaml
logging:
  level:
    com.tianji: debug
