server:
  port: 8081  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: auth-service
encrypt:
  key-store:
    alias: tjxt  #别名
    location: classpath:tjxt.jks  #KeyStore 证书库名称
    password: tj123321   #证书库密码
    secret: tj123321   #秘钥
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.auth.controller
    title: 天机学堂 - 权限微服务接口文档
    description: 该服务用于管理权限相关信息
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
  auth:
    resource:
      enable: true
      includeLoginPaths:
        - /menus/me
        - /accounts/logout
  jdbc:
    database: tj_auth
