server:
  port: 8094  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: aigc-service
  main:
    allow-circular-references: true # 允许循环引用
tj:
  swagger:
    enable: true
    package-path: com.tianji.aigc.controller
    title: 天机学堂 - AIGC接口文档
    description: 该服务包含AI相关功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhangzhijun@itcast.cn
    version: v1.0
    enableResponseWrap: true
  auth:
    resource:
      enable: true
      excludeLoginPaths:
        - /chat/text
  jdbc:
    database: tj_aigc #指定使用的数据库名
  ai:
    dashscope:
      key: ${ALIYUN_API_KEY}
      app-agent:
        id: xxxxxxxxx
        tools:
          - "tool_xxxxx"
          - "tool_xxxxx"
    openai:
      key: ${OPENAI_API_KEY}
    prompt:
      system:
        chat:
          data-id: system-chat-message.txt
          group: DEFAULT_GROUP
          timeout-ms: 20000
        route-agent:
          data-id: route-agent-system-message.txt
        recommend-agent:
          data-id: recommend-agent-system-message.txt
        buy-agent:
          data-id: buy-agent-system-message.txt
        consult-agent:
          data-id: consult-agent-system-message.txt
        knowledge-agent:
          data-id: knowledge-agent-system-message.txt
        text:
          data-id: text-system-chat-message.txt
    memory:
      max: 100 #存储最大的聊天记录数
      type: Redis # Redis / MYSQL / MongoDB
    chat-type: ENHANCE # ROUTE / ENHANCE / APP
