spring:
  cloud:
    nacos:
      server-addr: 172.17.2.76:8848 # nacos注册中心
      username: nacos
      password: nacos
      discovery:
        namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0
        group: DEFAULT_GROUP
        ip: 172.17.2.76
  config:
    import:
      - nacos:${spring.application.name}.yaml # 导入本服务的配置
      - nacos:shared-spring.yaml # 共享spring配置
      - nacos:shared-redis.yaml # 共享redis配置
      - nacos:shared-logs.yaml # 共享日志配置
      - nacos:shared-feign.yaml # 共享feign配置
  elasticsearch:
    uris: http://172.17.2.76:19200
  ai:
    dashscope:
      api-key: ${tj.ai.dashscope.key}
      chat:
        options:
          model: qwen2.5-3b-instruct
        enabled: true
      embedding:
        enabled: true
    openai:
      base-url: https://api.chatanywhere.tech
      api-key: ${tj.ai.openai.key}
      chat:
        options:
          model: "gpt-3.5-turbo-ca"
#          model: "gpt-3.5-turbo"
        enabled: false
      embedding:
        options:
          model: text-embedding-3-small
        enabled: false
    vectorstore:
      elasticsearch:
        initialize-schema: true
        dimensions: 1536
logging:
  level:
    com.tianji: debug
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
