server:
  port: 8094
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: local
  application:
    name: aigc-service
  main:
    allow-circular-references: true

# 公共配置分组
tj:
  # 接口文档配置
  swagger:
    enable: true
    package-path: com.tianji.aigc.controller
    title: 智慧MOOC - AIGC接口文档
    description: 该服务包含AIGC模块相关功能
    contact-name: 研究院
    contact-url: http://www.itcast.cn/
    contact-email: 1418875140@qq.com
    version: v1.0
    enableResponseWrap: true

  # 认证配置
  auth:
    resource:
      enable: true
      # excludeLoginPaths:
      #   - /chat/text

  # 数据库基础配置
  jdbc:
    database: tj_aigc

  # AI基础配置
  ai:
    memory:
      max: 100
      type: Redis # MYSQL | MongoDB | Redis
    chat-type: ENHANCE
    audio-type: DASHSCOPE
    splitter:
      max-chunk-size: 2000
      overlap-size: 100
      min-chunk-size: 100
    # AI提示词配置
    prompt:
      system:
        chat:
          data-id: system-chat-message.txt
          group: DEFAULT_GROUP
          timeout-ms: 20000
        route-agent:
          data-id: route-agent-system-message.txt
        recommend-agent:
          data-id: recommend-agent-system-message.txt
        buy-agent:
          data-id: buy-agent-system-message.txt
        consult-agent:
          data-id: consult-agent-system-message.txt
        knowledge-agent:
          data-id: knowledge-agent-system-message.txt
        text:
          data-id: text-system-chat-message.txt

  # 阿里云OSS配置
  ali:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
      access-id: ${OSS_ACCESSKEY_ID}
      access-key: ${OSS_ACCESSKEY_SECRET}
      bucket: web-shenqi