server:
  port: 8086  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: course-service
  main:
    allow-circular-references: true
tj:
  swagger:
    enable: true
    package-path: com.tianji.course.controller
    title: 天机学堂 - 课程系统接口文档
    description: 该服务包含课程管理相关功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
    enableResponseWrap: true
  auth:
    resource:
      enable: false
  jdbc:
    database: tj_course
