server:
  port: 8093  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: data-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.data.controller
    title: 天机学堂 - 数据中心接口文档
    description: 该服务包含数据看板统计的功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
  jdbc:
    database: tj_data
  auth:
    resource:
      enable: true
