spring:
  cloud:
    nacos:
      server-addr: 192.168.150.101:8848 # nacos注册中心
      username: nacos
      password: nacos
      discovery:
        namespace: f923fb34-cb0a-4c06-8fca-ad61ea61a3f0
        group: DEFAULT_GROUP
        ip: 192.168.150.1
  config:
    import:
      - nacos:${spring.application.name}.yaml # 导入本服务的配置
      - nacos:shared-spring.yaml # 共享spring配置
      - nacos:shared-redis.yaml # 共享redis配置
      - nacos:shared-mybatis.yaml # 共享mybatis配置
      - nacos:shared-logs.yaml # 共享日志配置
      - nacos:shared-feign.yaml # 共享feign配置
      - nacos:shared-mq.yaml # 共享mq配置
      - nacos:shared-xxljob.yaml # 共享mq配置
      - nacos:shared-seata.yaml # 共享seata配置
logging:
  level:
    com.tianji: debug
