server:
  port: 8089  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
  error:
    include-message: always #返回的响应体带上message
spring:
  profiles:
    active: local
  application:
    name: exam-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.exam.controller
    title: 天机学堂 - 考试中心接口文档
    description: 该服务提供题目管理、考试管理、数据统计等功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
  jdbc:
    database: tj_exam
  auth:
    resource:
      enable: false
