server:
  port: 8088  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: trade-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.trade.controller
    title: 天机学堂 - 交易中心接口文档
    description: 该服务提供购物车、订单管理等功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
  jdbc:
    database: tj_trade
  auth:
    resource:
      enable: true
      excludeLoginPaths:
        - "/order-details/enrollNum"
