server:
  port: 8082  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: user-service
tj:
  swagger:
    enable: true
    enableResponseWrap: true
    package-path: com.tianji.user.controller
    title: 天机学堂 - 用户中心接口文档
    description: 该服务用户管理、用户信息管理
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
  auth:
    resource:
      enable: false
      excludeLoginPaths:
        - /students/register
        - /users/detail/{isStaff}
        - /users/list
        - GET:/users/{id}
        - /users/{id}/type
        - /users/ids
        - /users/me
  jdbc:
    database: tj_user
