server:
  port: 8084  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: media-service
tj:
  swagger:
    enable: true
    package-path: com.tianji.media.controller
    title: 天机学堂 - 媒资中心接口文档
    description: 该服务包含图片管理、媒资管理等
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
    enableResponseWrap: true
  auth:
    resource:
      enable: true
      excludeLoginPaths:
        - /medias/signature/play
  jdbc:
    database: tj_media
  platform:
    file: TENCENT
#    file: ALI
    media: TENCENT
  ali:
    accessId: "*******"
    accessKey: "*******"
    oss:
      endpoint: "*******"
      bucket: "*******"
  tencent:
    appId: 1259405500
    secretId: AKIDTqzwf5UfdNs79weDetuhGkwAE3hFdnlV
    secretKey: X4SdZ6Xs1vc9RTItHSRDl6FD0c0BKGyT
    vod:
      enable: true
      vodValidSeconds: 7776000
      region: "ap-shanghai"
      procedure: "wisehub-base"
      urlKey: "HZFlxjPYoOm5AfShupOx"
      pfcg: "basicDrmPreset"
    cos:
      enable: true
      region: "ap-nanjing"
      bucket: tianji
      multipartUploadThreshold: 5242880 # 5mb，触发分片上传的阈值
      minimumUploadPartSize: 1048576 # 1mb，分片的最小大小
