server:
  port: 8083  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  profiles:
    active: local
  application:
    name: search-service
tj:
  swagger:
    enable: true
    package-path: com.tianji.search.controller
    title: 天机学堂 - 搜索系统接口文档
    description: 该服务包含课程搜索、兴趣推荐等相关功能
    contact-name: 传智教育·研究院
    contact-url: http://www.itcast.cn/
    contact-email: zhanghuyi@itcast.cn
    version: v1.0
    enableResponseWrap: true
  auth:
    resource:
      enable: true
      includeLoginPaths:
        - /interests/**
        - /courses/admin
  jdbc:
    database: tj_search
